version: '2.1'
orbs:
  android: circleci/android@2.4.0
jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2
      - image: cimg/android:2024.01
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Copy SDK License
          command: printf "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n" > ~/android-sdk-linux/licenses/android-sdk-license
      - run:
          name: Create local.properties
          command: echo "sdk.dir=$ANDROID_HOME" > local.properties
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
workflows:
  test:
    jobs:
      - test
