version: '2.1'
orbs:
  android: circleci/android@2.4.0
jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2
      - image: cimg/android:2024.01
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
workflows:
  test:
    jobs:
      - test