version: '2.1'
orbs:
  android: circleci/android@2.4.0
jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2
      - image: cimg/android:2024.01
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
workflows:
  test:
    jobs:
      - test