version: '2.1'
orbs:
  android: circleci/android@2.4.0
jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0.2
      - image: cimg/android:2024.01
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Run Build
          command: ./gradlew build
workflows:
  test:
    jobs:
      - test
